#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
root="$( cd "$(dirname "$0")"; cd ..; pwd -P )"

cd "$root"

cert_filename="$( terraform output -raw ca_filename )"
cert_path="/usr/local/share/ca-certificates/$cert_filename"

ca_cert="$( terraform output -raw ca_cert )"
echo "$ca_cert" | sudo tee -a "$cert_path" >/dev/null
sudo update-ca-certificates

echo "Installed the ca certificate at $CERT_PATH"
