#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
root="$( cd "$(dirname "$0")"; cd ..; pwd -P )"

cd "$root"

base_dn="$( terraform output -raw ldap_base_dn )"
host="$( terraform output -raw ldap_host )"
bind_dn="cn=admin,$base_dn"
bind_password="$( terraform output -raw ldap_admin_password )"

ldapsearch -x -b "$base_dn" \
  -H "ldaps://$host" \
  -D "$bind_dn" \
  -w "$bind_password"
